layout_spectrum: 0.1842105
color:
  saturation: 0.217508
  brandStrength: 0.7427498
  lightness: 0.4645543
  brandColors:
    - '#C8C6BC'
    - '#020302'
    - '#6D6F6E'
    - '#C53039'
    - '#FCFFFF'
  rhythmicContrast: 0.443072
typography_spectrum: 0.1390978
name: Manu Henriquez
